[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8.4"
reqwest = { version = "0.12", features = ["json", "stream"] }
tracing = "0.1"
